### ISSUE TITLE
[BUG] can not run the demo 

### ISSUE THREAD

**Issue by Jamlee** [fen-land/deno-fen#5]
**Describe the bug**
```
➜  tmp cat main.ts 
import { Server } from "https://raw.githubusercontent.com/fen-land/deno-fen/v0.7.1/server.ts";
const s = new Server();
// pls keep in mind that you may add an async function as controller
s.setController(async context => {
  context.body = "It's alive!";
});
s.port = 1882;
s.start();
                                                                                                                                                                         ➜  tmp deno main.ts
Compiling file:///home/jamlee/WorkTmp/tmp/main.ts
Downloading https://deno.land/x/std@v0.3.0/http/deno... NOT FOUND
Uncaught NotFound: Cannot resolve module "deno" from "/home/jamlee/.cache/deno/deps/https/deno.land/x/std@v0.3.0/http/server.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:33:12)
    at maybeThrowError (deno/js/errors.ts:39:15)
    at sendSync (deno/js/dispatch.ts:75:5)
    at fetchModuleMetaData (deno/js/os.ts:80:19)
    at _resolveModule (deno/js/compiler.ts:249:38)
    at resolveModuleNames (deno/js/compiler.ts:479:35)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:118650:138)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:86767:127)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:87001:24)
➜  tmp deno -v
deno: 0.3.3
v8: 7.4.238
typescript: 3.3.3333
➜  tmp 

```

the deno version is:

```
➜  tmp deno -v
deno: 0.3.3
v8: 7.4.238
typescript: 3.3.3333

```

**Comment by mxz96102** [comment]
Hello, thanks for your issue,
Can you try to run
`deno -r -A main.ts`
I'm trying to figure out where is this https://deno.land/x/std@v0.3.0/http/deno import from.
thx~

**Comment by mxz96102** [comment]
Thanks for your issue
it seems like because of the deno 0.3.3 can't match deno_std 0.3.0, I'm on my way to publish 0.7.2

**Comment by Jamlee** [comment]
i am  looking forward to your new version

**Comment by mxz96102** [comment]
now you can switch version to v0.7.2 and try again
```typescript
import { Server } from "https://raw.githubusercontent.com/fen-land/deno-fen/v0.7.2/server.ts";
```
feel free to reopen this issue if you are still in trouble

**Comment by Jamlee** [comment]
nice, it is worked.
